# Site settings
title: GALT-Central Texas
email: website@galtx-centex.org
description: "Adopting retired racing greyhounds in Austin, Texas and surrounding areas"
baseurl: ""
url: "https://galtx-centex.org"

# Build settings
permalink: pretty
exclude: ["vendor", "script", "Rakefile", "Gemfile*", "README*"]
collections:
  greyhounds:
    output: true
pagination:
  enabled: true
  permalink: /:num/
plugins:
  - jekyll-paginate-v2
