name: Update a Greyhound

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
      status:
        type: choice
        options:
          - no update
          - pending
          - adopted
          - medhold
          - permafoster
          - deceased
        default: no update
      catsafe:
        type: choice
        options:
          - no update
          - yes
          - no
        default: no update

env:
  INPUTS: ${{ toJSON(inputs) }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
